version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: inprod
    ports:
      - "5438:5432"
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./inproddb.sql:/docker-entrypoint-initdb.d/create_tables.sql
